[build-system]
requires = ["flit_core >=3.2,<4",]
build-backend = "flit_core.buildapi"

[project]
name = "teamod"
authors = [{name = "Sarang S. Bhagwat", email = "sarang.bhagwat.git@gmail.com"}]
dynamic = ["version", "description"]
